package com.model;
// Generated Jun 11, 2019 4:21:47 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * L1Category generated by hbm2java
 */
@Entity
@Table(name = "l1_category", catalog = "flipkart")
public class L1Category implements java.io.Serializable {

	private Long l1CategoryId;
	private String l1CategoryName;
	private Set<L2Category> l2Categories = new HashSet<L2Category>(0);

	public L1Category() {
	}

	public L1Category(String l1CategoryName, Set<L2Category> l2Categories) {
		this.l1CategoryName = l1CategoryName;
		this.l2Categories = l2Categories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "L1_CATEGORY_ID", unique = true, nullable = false)
	public Long getL1CategoryId() {
		return this.l1CategoryId;
	}

	public void setL1CategoryId(Long l1CategoryId) {
		this.l1CategoryId = l1CategoryId;
	}

	@Column(name = "L1_CATEGORY_NAME", length = 256)
	public String getL1CategoryName() {
		return this.l1CategoryName;
	}

	public void setL1CategoryName(String l1CategoryName) {
		this.l1CategoryName = l1CategoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "l1Category")
	public Set<L2Category> getL2Categories() {
		return this.l2Categories;
	}

	public void setL2Categories(Set<L2Category> l2Categories) {
		this.l2Categories = l2Categories;
	}

}
