package com.model;
// Generated Jun 11, 2019 4:21:47 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * L2Category generated by hbm2java
 */
@Entity
@Table(name = "l2_category", catalog = "flipkart")
public class L2Category implements java.io.Serializable {

	private Long l2CategoryId;
	private L1Category l1Category;
	private String l2CategoryName;
	private Set<L3Category> l3Categories = new HashSet<L3Category>(0);

	public L2Category() {
	}

	public L2Category(L1Category l1Category, String l2CategoryName) {
		this.l1Category = l1Category;
		this.l2CategoryName = l2CategoryName;
	}

	public L2Category(L1Category l1Category, String l2CategoryName, Set<L3Category> l3Categories) {
		this.l1Category = l1Category;
		this.l2CategoryName = l2CategoryName;
		this.l3Categories = l3Categories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "L2_CATEGORY_ID", unique = true, nullable = false)
	public Long getL2CategoryId() {
		return this.l2CategoryId;
	}

	public void setL2CategoryId(Long l2CategoryId) {
		this.l2CategoryId = l2CategoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "L1_CATEGORY_ID", nullable = false)
	public L1Category getL1Category() {
		return this.l1Category;
	}

	public void setL1Category(L1Category l1Category) {
		this.l1Category = l1Category;
	}

	@Column(name = "L2_CATEGORY_NAME", nullable = false, length = 256)
	public String getL2CategoryName() {
		return this.l2CategoryName;
	}

	public void setL2CategoryName(String l2CategoryName) {
		this.l2CategoryName = l2CategoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "l2Category")
	public Set<L3Category> getL3Categories() {
		return this.l3Categories;
	}

	public void setL3Categories(Set<L3Category> l3Categories) {
		this.l3Categories = l3Categories;
	}

}
