package com.model;
// Generated Jun 11, 2019 4:21:47 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * L3Category generated by hbm2java
 */
@Entity
@Table(name = "l3_category", catalog = "flipkart")
public class L3Category implements java.io.Serializable {

	private long l3CategoryId;
	private L2Category l2Category;
	private String l3CategoryName;
	private Set<Products> productses = new HashSet<Products>(0);

	public L3Category() {
	}

	public L3Category(long l3CategoryId, L2Category l2Category, String l3CategoryName) {
		this.l3CategoryId = l3CategoryId;
		this.l2Category = l2Category;
		this.l3CategoryName = l3CategoryName;
	}

	public L3Category(long l3CategoryId, L2Category l2Category, String l3CategoryName, Set<Products> productses) {
		this.l3CategoryId = l3CategoryId;
		this.l2Category = l2Category;
		this.l3CategoryName = l3CategoryName;
		this.productses = productses;
	}

	@Id

	@Column(name = "L3_CATEGORY_ID", unique = true, nullable = false)
	public long getL3CategoryId() {
		return this.l3CategoryId;
	}

	public void setL3CategoryId(long l3CategoryId) {
		this.l3CategoryId = l3CategoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "L2_CATEGORY_ID", nullable = false)
	public L2Category getL2Category() {
		return this.l2Category;
	}

	public void setL2Category(L2Category l2Category) {
		this.l2Category = l2Category;
	}

	@Column(name = "L3_CATEGORY_NAME", nullable = false, length = 256)
	public String getL3CategoryName() {
		return this.l3CategoryName;
	}

	public void setL3CategoryName(String l3CategoryName) {
		this.l3CategoryName = l3CategoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "l3Category")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
